version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
  mysql_db:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: spring_api_db
      MYSQL_USER: antonio
      MYSQL_PASSWORD: w3lcome
      MYSQL_ROOT_PASSWORD: root_pwd