package com.example.springbootapi;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller //this means this clas is a controller
@RequestMapping(path="/user") //this means URL'S start with /user (after application path)

public class MainController {
    @Autowired //this means to get the bean called userRepository
    //which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping
    public @ResponseBody String addNewUser (@RequestBody User user) {
       User localUser = new User();
       localUser.setEmail(user.getEmail());
       localUser.setName(user.getName());
       userRepository.save(localUser);
       return "saved";
    }

    @GetMapping
    public @ResponseBody Iterable<User> getAllUsers() {
        // this returns a JSON or XML with the users
        return userRepository.findAll();
    }
}